### ISSUE TITLE
Crypto not found in React Native

### ISSUE THREAD

**Issue by tapz** [emn178/js-sha256#11]
React Native gives the following error: "Unable to resolve module 'crypto' from '/js-sha26/src/sha256.js': Module does not exist i the module map".

**Comment by emn178** [comment]
I will check when I have time.

**Comment by emn178** [comment]
I can't build a workable React Native project. I tried
https://facebook.github.io/react-native/docs/getting-started.html
https://github.com/taskrabbit/ReactNativeSampleApp
https://github.com/kauffecup/react-native-web-hello-world

Can you give me a workable project for test?

**Comment by shumbawumba** [comment]
The latest version of `js-sha256` works with `react-native` 0.50.4 and `react` 16.  To reproduce:

- Initialize a new project:

```bash
$ react-native init Sha256
$ cd Sha256
$ npm install --save js-sha256
```

- Add the import to App.js and use the library:

```js
/* at the top */
import * as SHA from 'js-sha256';

/* in the render function */
        <Text style={styles.welcome}>
          {SHA.sha256("foobar")}
        </Text>
```

- Build and run the project:

```bash
$ react-native run-ios
```

**Comment by lll000111** [comment]
Related?

https://github.com/emn178/js-sha256/issues/7
