### ISSUE TITLE
Rollupjs build complains about the use of eval in this library.

### ISSUE THREAD

**Issue by siva-I** [emn178/js-sha256#18]
(!) Use of eval is strongly discouraged
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
node_modules/js-sha256/src/sha256.js
84: 
85:   var nodeWrap = function (method, is224) {
86:     var crypto = eval("require('crypto')");
                     ^
87:     var Buffer = eval("require('buffer').Buffer");
88:     var algorithm = is224 ? 'sha224' : 'sha256';
...and 1 other occurrence
created dist/transactionmgmt.dev.js in 4.7s

[2018-06-21 10:33:00] waiting for changes...
<img width="510" alt="screen shot 2018-06-21 at 10 35 13 am" src="https://user-images.githubusercontent.com/9806313/41735544-d2abbe48-753e-11e8-836d-2071125cddb5.png">

**Comment by emn178** [comment]
This is because emn178/js-md5#8
And I found it won't polyfill unused code in this way.

**Comment by gmiklich** [comment]
Can it be changed to a dynamic import or anything along those lines to avoid the use of `eval()`?

**Comment by lmm-git** [comment]
Even more, this prevents us from **not** using 'unsafe-eval' in our Content Security Policy. Any chance that this one get fixed?

**Comment by ivands** [comment]
It also breaks in vitejs

**Comment by hansottowirtz** [comment]
As a fix, you can replace the eval strings in the library during build.
In `rollup.config.js`:

```js
import replace from "rollup-plugin-re";

export default {
  ...,
  plugins: [
    replace({
      patterns: [
        {
          match: /js-sha256/,
          test: `eval("require('crypto')")`,
          replace: `require('crypto')`
        },
        {
          match: /js-sha256/,
          test: `eval("require('buffer').Buffer")`,
          replace: `require('buffer').Buffer`
        }
      ],
    }),
  ]
}
```

**Comment by juhoha** [comment]
An alternative to suppress warnings in `vite.config.js`:

```es6
export default defineConfig({
  build: {
    rollupOptions: {
      onwarn: ({ loc }) => {
        if (loc?.file?.match(/js-sha256\/src\/sha256.js$/))
            return;
      } 
  }
});
```

**Comment by emn178** [comment]
remove eval in v0.10.0
