### ISSUE TITLE
Hmac update question

### ISSUE THREAD

**Issue by epilkis** [emn178/js-sha256#19]
I think It's more of a question than an issue because I am probably not using the library correctly. After I run update on the hmac second time, shouldn't the hash change? Why doesn't it and how would I properly use the update function? See example below.

var hash = sha256.hmac.create('mykey');
hash.update(mykey,'Message one to hash');
hash.hex() is ABC
hash.update(mykey,'Message two to hash');
hash.hex() is still ABC

**Comment by emn178** [comment]
sorry for late response

1. you can only pass message after create 
```JavaScript
// incorrect
hash.update(mykey,'Message one to hash');

// correct
hash.update('Message one to hash');
```

2. the hash will freeze after you fetch result
```JavaScript
hash.hex(); // freeze
hash.update('Message two to hash'); // not work
```
I think it's better to throw an error when users try to modify the frozen data.
