### ISSUE TITLE
Outdated typescript definition

### ISSUE THREAD

**Issue by lucaelin** [emn178/js-sha256#20]
Typescript claims that there is no default export when using `import sha256 form 'js-sha256';`.
The `index.d.ts` claims that only two named exports exists (sha256 and sha224) but this does not seem to be the case anymore as `import * as sha from 'js-sha256';` shows named as well as a default export. 
Trying to `import { sha256, sha224 } from 'js-sha256';` fails as well, as the real export of this module is not an object containing these functions, but an objects that contains the default in on property and named exports inside another. 
A workaround is to `import * as sha from 'js-sha256';` and then use `(sha as any).default(message)`, but this is considered bad practice as it's loosing the type information and requires low level interaction with the es-module system.

**Comment by emn178** [comment]
What environment do you use? I can't reproduce this issue. I try this
```TypeScript
import { sha256 } from 'js-sha256';

console.log(sha256('...'));

```
and packages
```
    "js-sha256": "^0.9.0",
    "ts-node": "^7.0.0",
    "typescript": "^2.9.2"
```
and works

**Comment by lucaelin** [comment]
Ohh silly me! I forgot to mention that I use rollup to bundle the app, and it's rollup that's giving me the error. Typescript itself is fine with the import, you are absolutely correct. Sorry for being lazy when filing the issue.
But the problem remains: Due to the mismatch between the typescript definition and the structure that is exported when using rollup, I cannot satisfy both of them.
I just confirmed that by adding a default export to the typescript definition, rollup with typescript works fine when using the default import, but typescript alone breaks as it cannot find a default import. Typescript using the named export continues working (but it wont warn you about the failing default export), while rollup with typescript breaks in that case, as it cannot find the named export...
I'm sorry that this is getting a little messy.. If there is anything i can do to help debugging this, please let me know!

**Comment by emn178** [comment]
I tried rollup with [rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript), and it still works.

```
MacBook-Pro:ts-test emn178$ rollup -c --format cjs --file a.js
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
entry is now input

./index.ts → a.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
js-sha256 (imported by index.ts)
created a.js in 79ms
```

**Comment by lucaelin** [comment]
Your log hints, that you've excluded the library from the bundle, correct? 
I've created a (not so) small reproduction of the 3 different approaches i could think of in https://github.com/lucaelin/jssha-bug 
I've documented my results in the readme, let's hope we can agree on the results from that :smile: 
I truly appreciate your interest in this bug!

**Comment by emn178** [comment]
Looks like `rollup-plugin-commonjs` can not parse the exports correctly. [see](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports)

You have to define it.
```JavaScript
commonjs({
  namedExports: {
    'js-sha256': [ 'sha256', 'sha224' ]
  }
})
```

**Comment by lucaelin** [comment]
Yes, that does solve it for me. Thanks for taking the time! :)
