### ISSUE TITLE
Different output on online-tools and while using the lib

### ISSUE THREAD

**Issue by emil14** [emn178/js-sha256#27]
![Screenshot from 2021-02-02 15-07-36](https://user-images.githubusercontent.com/6453537/106598215-7c384a00-6568-11eb-9e0d-25761f6e197f.png)

```js
sha256.hex('b03cadd31554cdbe6e67fc0ad2f0ffeb8aae91de4f0657c3ba6fc11b94b85e46') === '182ee7d99a515fdd59d25d5d8a2a263b52097fd212e169f2df208a6c4b7e1c73'
```

why it gives `182ee7d99a515fdd59d25d5d8a2a263b52097fd212e169f2df208a6c4b7e1c73` instead of `2656b1039a88fbd83409795d31480d3090ec797488df19cbef2b70c69df87c29`? am I using the library in the wrong way?

thank you

**Comment by emn178** [comment]
sha256.hex means output in hex string, not input.

convert hex to bytes refer to this
https://github.com/emn178/online-tools/blob/master/js/main.js#L4


Emil Valeev <notifications@github.com> 於 2021年2月2日 週二 下午8:10寫道：

**Comment by emil14** [comment]
> convert hex to bytes refer to this

Maybe it's better to throw an exception or somehow prevent users from wrong usage

Anyway thank you
