### ISSUE TITLE
When will the version be updated? How often is the update?

### ISSUE THREAD

**Issue by MandaJC** [emn178/js-sha256#29]

**Comment by nicolasverlhiac** [comment]
Hi @MandaJC , what do you need for the next update ?

**Comment by vovacodes** [comment]
Have the same question about maintainability. My main concern is the use of `eval` that causes https://github.com/emn178/js-sha256/issues/26. The was no reaction to from the author, and the last commit was in 2017 so I wonder if I should just fork it or offer the author some help with maintaining this one. @emn178 would you be interested in giving someone else maintainer's permissions?

**Comment by jonkoops** [comment]
I believe this issue can be closed as a new version without `eval()` was released just a month ago.
