### ISSUE TITLE
The files downloaded from npm are different from the files downloaded from github

### ISSUE THREAD

**Issue by nolsherry** [emn178/js-sha256#3]
Hello @emn178,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I have downloaded the version 0.3.0 in [npm](https://www.npmjs.com/package/js-sha256), but I found that the files are not the same as the files which downloaded from [github](https://github.com/emn178/js-sha256), 
Could you help me update the files in npm? thank you very much!

cdnjs/cdnjs#5766

**Comment by emn178** [comment]
Hi, I added files to npm package in v0.3.1.

**Comment by nolsherry** [comment]
@emn178, thanks for your help. :)
