### ISSUE TITLE
How to decrypt

### ISSUE THREAD

**Issue by 0completist** [emn178/js-sha256#30]

**Comment by sentinelb51** [comment]
![image](https://user-images.githubusercontent.com/75678325/143837417-3fe12d17-ab9f-4569-8051-e30f9302ed93.jpeg)

**Comment by ellieeet123** [comment]
haha, good one

**Comment by marco910** [comment]
Any updates on this, how I can decrypt a string with that library?

**Comment by ThomasLobker** [comment]
> Any updates on this, how I can decrypt a string with that library?

It's not encryption. You cannot decrypt. You can only sign and verify the signature.
