### ISSUE TITLE
Deprecate library and reccomend standardized APIs

### ISSUE THREAD

**Issue by jonkoops** [emn178/js-sha256#33]
Since the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) is now widely supported both on the Web and Node.js this library serves little to no purpose in modern JavaScript development. This library is also very clearly no longer actively maintained.

Given these arguments I would like to propose this library be deprecated as follows:
- Add a section to the README instructing users to use the Web Crypto API instead.
- Deprecate all versions of the NPM package using [`npm deprecate`](https://docs.npmjs.com/cli/v8/commands/npm-deprecate).
- Archive the repository on Github.

**Comment by jonkoops** [comment]
ping @emn178

**Comment by phtdacosta** [comment]
I may disagree with you when it comes to "serves little to no purpose". WebCryptoAPI requires HTTPS to work wheareas @emn178's library does work in both HTTP and HTTPS. It IS really handy.

**Comment by jonkoops** [comment]
Realistically, in what scenario would you deploy an application without HTTPS?

**Comment by phtdacosta** [comment]
That's half the catch!

1. For testing, in local environments, it is useful as a "decoy" while you do not put it for production over the www
2. In very resource-constrained environments where you need to be precise as a needle, (IOT for example) you may only need specific libraries to work with and having HTTPS may be complete overkilll or even an actual "threadlock" to deal with
3. This one is much less common but when dealing with legacy systems one also may need to use some "silver tape" solution like this

From my personal experience, those are the only three **specific** scenarios where this library is _still_ greatly useful to work with.

**Comment by jonkoops** [comment]
1. In this case `localhost` is considered a secure domain, so the Crypto API will work. If someone is testing with a custom domain locally they could use a self-signed certificate or whitelist their domain.
2. I guess it could be the case that some IoT devices are not on a secure connection, but I sincerely doubt that running an HTTPS connection is that resource constrained.
3. Legacy solutions use legacy code, nobody is stopping folks from running old code (including this lib).

**Comment by f478ccf2** [comment]
The Web Crypto API for hashing is not very good, there might be some cases for when this library might be needed, those cases be any other case than encrypting an entire chunk of plaintext at a time.

**Comment by jonkoops** [comment]
> The Web Crypto API for hashing is not very good

Could you elaborate on this a little? I'd be curious if there is a specific example to this.

**Comment by f478ccf2** [comment]
It's good for only one purpose, which is hashing small amounts of data. There's no way to hash data in chunks (i.e create a hash object and update data), it's only good for small amounts of data, because it can only encrypt data in one big chunk. If this  functionality was added (maybe even with native speed!), I would definitely stop using this library (or any other SHA library), but for now it does have a use.

**Comment by thekip** [comment]
+1 for non-async usage. Example i want to make a universal function which would work in node and browser. I might use standard WebCrypro api, but it's async only, and my use case is synchronous (generating ids inside babel transformation).

**Comment by f478ccf2** [comment]
Well, if you are going for speed and can fit the entire file into memory, SubtleCrypto may be faster. It uses BoringSSL's crypto functions under the hood (AFAIK), which may use CPU intrinsics as available to speed up the computation. On my laptop with an 11th-gen Intel i3, I can hash a 500MB Uint8Array in 723ms.

**Comment by jonkoops** [comment]
Closing this, as there obviously seems to be a common use-case for a synchronous API.
