### ISSUE TITLE
v0.3.0 -> v0.3.1 breaks builds

### ISSUE THREAD

**Issue by d-a-n** [emn178/js-sha256#4]
Hi,

since version 0.3.1 my builds no longer work.

> var sha256 = require("js-sha256");
> var sha = sha256("my string");
> TypeError: '[object Object]' is not a function (evaluating 'sha256("my string")')

Breaking changes should be done in a major version, not a patch.

**Comment by emn178** [comment]
What's your environment? It works for me.

**Comment by emn178** [comment]
I updated Node.js env detection in 0.3.1. It seems to cause your problem. I guess you not run in a Node.js env. I changed detection to CommonJS in 0.3.2. It should work. Please help me to try if it fix this problem. Thanks.
