### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by WhyEvenTry** [emn178/js-sha256#6]
How hard would it be to add stream support? Like node.js crypto, example usage. Stream meaning "to create the hash piece by piece", the crypto code doesn't actually see (or care about) the stream object.

```javascript
// Given: a stream$readable

const cryptoHashObj = crypto.createHash('sha256');

stream.once('finish', () => {
    const hash: SHA256Hash = cryptoHashObj.digest('hex');
    // do stuff with hash
});

stream.on('data', (data: Buffer) => {
    cryptoHashObj.update(data);
});
```

Just asking!

Looking at the code, I guess I just have to rerun the `do` loop while keeping the values of the variables for the next run. Or do I have to make sure of block-sizes in the middle updates, meaning I may have to keep a few bytes back for the next run because it's not a full block (yet)? I really want to avoid to having to understand this algorithm. Not that it's hard, but I've got enough other stuff...

**Comment by emn178** [comment]
v0.5.0 added this feature. You can try it.

**Comment by WhyEvenTry** [comment]
Cool! Downloaded.

Long-term, you could put in a vote for the (actually already partially implemented in browsers) WebCrypto API to support streaming, inexplicably some people make a big deal about it and suggest to "close as WontFix":

https://github.com/w3c/webcrypto/issues/73
